-- Esquema de trazabilidad de carrocerías con defectos (Cronos)
-- Postgres puro: corre igual en Supabase (cloud) o en un servidor de planta (on-premise).

create table colores (
  cest   text primary key,
  nombre text
);

create table tipos_falla (
  id                      smallint primary key,
  nombre                  text not null,
  usa_particularidad      boolean not null default false,
  requiere_particularidad boolean not null default false,
  activo                  boolean not null default true
);

create table particularidades (
  id     smallint primary key,
  codigo text unique not null,
  nombre text not null
);

create table operarios (
  id     bigint generated by default as identity primary key,
  nombre text not null,
  legajo text,
  rol    text not null check (rol in ('revision', 'box', 'supervisor')),
  activo boolean not null default true
);

-- Maestro de carrocerías. Se puebla importando el export del sistema de planta
-- (hoja CISDetailsDataActual) o al vuelo cuando revisión final carga un CIS nuevo.
create table unidades (
  id           bigint generated by default as identity primary key,
  cis          char(7) unique not null check (cis ~ '^[0-9]{7}$'),
  check_digit  smallint,
  cest         text references colores,
  st           text,
  ssc          text,
  smo          text,
  salida_linea timestamptz,
  creada_at    timestamptz not null default now()
);

-- Cada desvío de línea. Una unidad puede reingresar: nueva incidencia, historial intacto.
create table incidencias (
  id           bigint generated by default as identity primary key,
  unidad_id    bigint not null references unidades,
  estado       text not null check (estado in ('en_box', 'en_reparacion', 'espera_particularidad', 'liberada', 'caso_especial')),
  detectada_at timestamptz not null default now(),
  cerrada_at   timestamptz,
  notas        text
);

-- Regla de negocio: una sola incidencia abierta por carrocería.
create unique index una_abierta_por_unidad on incidencias (unidad_id) where cerrada_at is null;

-- Varias fallas por incidencia ("falta baúl y capot" = 2 filas).
create table incidencia_fallas (
  id                bigint generated by default as identity primary key,
  incidencia_id     bigint not null references incidencias on delete cascade,
  tipo_falla_id     smallint not null references tipos_falla,
  particularidad_id smallint references particularidades,
  descripcion       text,
  resuelta_at       timestamptz
);

-- Historial inmutable de cambios de estado: la fuente de todos los tiempos de ciclo.
create table eventos (
  id              bigint generated by default as identity primary key,
  incidencia_id   bigint not null references incidencias on delete cascade,
  estado_anterior text,
  estado_nuevo    text not null,
  operario_id     bigint references operarios,
  registrado_at   timestamptz not null default now(),
  observacion     text
);

create index eventos_incidencia on eventos (incidencia_id, registrado_at);
create index incidencias_abiertas on incidencias (estado) where cerrada_at is null;

-- Turnos de planta: mañana (06-14) y tarde (14-22).
create function turno(ts timestamptz) returns text
language sql immutable as $$
  select case
    when extract(hour from ts at time zone 'America/Argentina/Buenos_Aires') < 14 then 'Mañana'
    else 'Tarde'
  end
$$;

-- ── Vistas para Power BI ────────────────────────────────────────────────

create view v_en_piso as
select
  i.id as incidencia_id,
  u.cis,
  u.cest,
  c.nombre as color,
  i.estado,
  i.detectada_at,
  turno(i.detectada_at) as turno_deteccion,
  round((extract(epoch from now() - i.detectada_at) / 86400)::numeric, 1) as dias_en_piso,
  case
    when now() - i.detectada_at > interval '40 days' then 'rojo'
    when now() - i.detectada_at > interval '7 days' then 'ambar'
    else 'verde'
  end as semaforo,
  i.notas
from incidencias i
join unidades u on u.id = i.unidad_id
left join colores c on c.cest = u.cest
where i.cerrada_at is null;

create view v_tiempos_ciclo as
with hitos as (
  select
    incidencia_id,
    min(registrado_at) filter (where estado_nuevo = 'en_box') as detectada,
    min(registrado_at) filter (where estado_nuevo = 'en_reparacion') as inicio_reparacion,
    min(registrado_at) filter (where estado_nuevo = 'liberada') as liberada
  from eventos
  group by incidencia_id
)
select
  i.id as incidencia_id,
  u.cis,
  u.cest,
  turno(h.detectada) as turno_deteccion,
  h.detectada,
  h.liberada,
  round((extract(epoch from h.inicio_reparacion - h.detectada) / 3600)::numeric, 1) as horas_espera,
  round((extract(epoch from h.liberada - h.inicio_reparacion) / 3600)::numeric, 1) as horas_reparacion,
  round((extract(epoch from h.liberada - h.detectada) / 3600)::numeric, 1) as horas_totales
from hitos h
join incidencias i on i.id = h.incidencia_id
join unidades u on u.id = i.unidad_id;

create view v_pareto_fallas as
select
  t.nombre as tipo_falla,
  p.nombre as particularidad,
  u.cest,
  turno(i.detectada_at) as turno_deteccion,
  date_trunc('month', i.detectada_at) as mes,
  count(*) as cantidad
from incidencia_fallas f
join incidencias i on i.id = f.incidencia_id
join unidades u on u.id = i.unidad_id
join tipos_falla t on t.id = f.tipo_falla_id
left join particularidades p on p.id = f.particularidad_id
group by 1, 2, 3, 4, 5;

-- ── Catálogos ───────────────────────────────────────────────────────────

insert into tipos_falla (id, nombre, usa_particularidad, requiere_particularidad) values
  (1, 'Bollo', true, false),
  (2, 'Falta de particularidad', true, true),
  (3, 'Para repintar', false, false),
  (4, 'Ya repintada', false, false),
  (5, 'JyP', true, false),
  (6, 'Marca de operación', true, false),
  (7, 'Caso especial', false, false),
  (8, 'Otra anomalía', false, false);

insert into particularidades (id, codigo, nombre) values
  (1, 'CAPOT', 'Capot'),
  (2, 'BAUL', 'Baúl'),
  (3, 'PASX', 'Puerta anterior izq.'),
  (4, 'PADX', 'Puerta anterior der.'),
  (5, 'PPSX', 'Puerta posterior izq.'),
  (6, 'PPDX', 'Puerta posterior der.'),
  (7, 'GBSX', 'Guardabarro izq.'),
  (8, 'GBDX', 'Guardabarro der.'),
  (9, 'ZOC', 'Zócalo');

insert into operarios (nombre, rol) values
  ('Julián H.', 'supervisor'),
  ('Revisión 1', 'revision'),
  ('Revisión 2', 'revision'),
  ('Box 1', 'box'),
  ('Box 2', 'box');
