-- Esquema de trazabilidad de carrocerías con defectos (Cronos / KP1)
-- Compatible con Supabase (cloud) o Postgres on-premise.
-- Ejecutar en: Supabase → SQL Editor → New query → pegar todo → Run.

create table colores (
  cest   text primary key,
  nombre text,
  hex    text
);

create table tipos_falla (
  id                      smallint primary key,
  nombre                  text not null,
  usa_particularidad      boolean not null default false,
  requiere_particularidad boolean not null default false,
  activo                  boolean not null default true
);

create table particularidades (
  id     smallint primary key,
  codigo text unique not null,
  nombre text not null,
  tipo   text not null default 'cronos'
);

create table operarios (
  id     bigint generated by default as identity primary key,
  nombre text not null,
  legajo text,
  rol    text not null check (rol in ('revision', 'oleo', 'box', 'supervisor')),
  activo boolean not null default true,
  manual boolean not null default false
);

create table unidades (
  id           bigint generated by default as identity primary key,
  cis          text unique not null,
  check_digit  smallint,
  cest         text references colores,
  st           text default '',
  ssc          text default '',
  smo          text default '',
  tipo         text not null default 'cronos',
  salida_linea timestamptz,
  creada_at    timestamptz not null default now()
);

create table incidencias (
  id           bigint generated by default as identity primary key,
  unidad_id    bigint not null references unidades,
  estado       text not null default 'en_espera'
               check (estado in ('en_espera', 'liberada', 'caso_especial')),
  origen       text not null default 'revision',
  turno        text,
  atribucion   text,
  detectada_at timestamptz not null default now(),
  cerrada_at   timestamptz,
  notas        text default ''
);

create unique index una_abierta_por_unidad on incidencias (unidad_id) where cerrada_at is null;

create table incidencia_fallas (
  id                bigint generated by default as identity primary key,
  incidencia_id     bigint not null references incidencias on delete cascade,
  tipo_falla_id     smallint not null references tipos_falla,
  particularidad_id smallint references particularidades,
  descripcion       text default '',
  resuelta_at       timestamptz
);

create table eventos (
  id              bigint generated by default as identity primary key,
  incidencia_id   bigint not null references incidencias on delete cascade,
  estado_anterior text,
  estado_nuevo    text not null,
  operario_id     bigint references operarios,
  turno           text,
  registrado_at   timestamptz not null default now(),
  observacion     text default ''
);

create index eventos_incidencia on eventos (incidencia_id, registrado_at);
create index incidencias_abiertas on incidencias (estado) where cerrada_at is null;

-- ── Habilitar Realtime ─────────────────────────────────────────────────
-- Supabase necesita esto para que los cambios se propaguen al instante.

alter publication supabase_realtime add table incidencias;
alter publication supabase_realtime add table incidencia_fallas;
alter publication supabase_realtime add table eventos;
alter publication supabase_realtime add table unidades;
alter publication supabase_realtime add table operarios;

-- ── Acceso sin autenticación ───────────────────────────────────────────
-- La app se usa dentro de la planta sin login. Estas políticas permiten
-- lectura y escritura desde el anon key de Supabase.

grant usage on schema public to anon, authenticated;
grant all on all tables in schema public to anon, authenticated;
grant all on all sequences in schema public to anon, authenticated;
alter default privileges in schema public grant all on tables to anon, authenticated;
alter default privileges in schema public grant all on sequences to anon, authenticated;

alter table colores          enable row level security;
alter table tipos_falla      enable row level security;
alter table particularidades enable row level security;
alter table operarios        enable row level security;
alter table unidades         enable row level security;
alter table incidencias      enable row level security;
alter table incidencia_fallas enable row level security;
alter table eventos          enable row level security;

create policy "acceso_libre" on colores          for all to anon, authenticated using (true) with check (true);
create policy "acceso_libre" on tipos_falla      for all to anon, authenticated using (true) with check (true);
create policy "acceso_libre" on particularidades for all to anon, authenticated using (true) with check (true);
create policy "acceso_libre" on operarios        for all to anon, authenticated using (true) with check (true);
create policy "acceso_libre" on unidades         for all to anon, authenticated using (true) with check (true);
create policy "acceso_libre" on incidencias      for all to anon, authenticated using (true) with check (true);
create policy "acceso_libre" on incidencia_fallas for all to anon, authenticated using (true) with check (true);
create policy "acceso_libre" on eventos          for all to anon, authenticated using (true) with check (true);

-- ── Catálogos ──────────────────────────────────────────────────────────

insert into colores (cest, nombre, hex) values
  ('979', 'Gris Silverstone', '#6A6E72'),
  ('249', 'Blanco Banchisa', '#F0EEE6'),
  ('619', 'Plata Bari', '#C9CBCD'),
  ('806', 'Negro', '#1E2124'),
  ('534', 'Blanco Alaska', '#FBFBFA'),
  ('978', 'Rojo', '#9E2B32'),
  ('504', 'Naranja (RAM)', '#D95B1E'),
  ('860', 'Azul (RAM)', '#1F4E8C');

insert into tipos_falla (id, nombre, usa_particularidad, requiere_particularidad, activo) values
  (1, 'Bollo', true, false, true),
  (2, 'Falta de particularidad', true, true, true),
  (3, 'Para repintar', false, false, false),
  (4, 'Ya repintada', false, false, false),
  (5, 'JyP', true, false, true),
  (6, 'Marca de operación', true, false, false),
  (7, 'Caso especial', false, false, true),
  (8, 'Otra anomalía', false, false, true);

insert into particularidades (id, codigo, nombre, tipo) values
  (1, 'CAPOT', 'Capot', 'cronos'),
  (2, 'BAUL', 'Baúl', 'cronos'),
  (3, 'PASX', 'Puerta anterior izq.', 'cronos'),
  (4, 'PADX', 'Puerta anterior der.', 'cronos'),
  (5, 'PPSX', 'Puerta posterior izq.', 'cronos'),
  (6, 'PPDX', 'Puerta posterior der.', 'cronos'),
  (7, 'GBSX', 'Guardabarro izq.', 'cronos'),
  (8, 'GBDX', 'Guardabarro der.', 'cronos'),
  (9, 'ZOC', 'Zócalo', 'cronos');

insert into operarios (nombre, rol) values
  ('Julián H.', 'supervisor'),
  ('Revisión 1', 'revision'),
  ('Revisión 2', 'revision'),
  ('Box 1', 'box'),
  ('Box 2', 'box');

-- ── Vistas para Power BI ───────────────────────────────────────────────

create or replace view v_en_piso as
select
  i.id as incidencia_id,
  u.cis,
  u.cest,
  c.nombre as color,
  u.tipo as tipo_unidad,
  i.estado,
  i.origen,
  i.turno as turno_deteccion,
  i.detectada_at,
  round((extract(epoch from now() - i.detectada_at) / 86400)::numeric, 1) as dias_en_piso,
  case
    when now() - i.detectada_at > interval '40 days' then 'rojo'
    when now() - i.detectada_at > interval '7 days'  then 'ambar'
    else 'verde'
  end as semaforo,
  i.notas
from incidencias i
join unidades u on u.id = i.unidad_id
left join colores c on c.cest = u.cest
where i.cerrada_at is null;

create or replace view v_pareto_fallas as
select
  t.nombre as tipo_falla,
  p.nombre as particularidad,
  u.cest,
  u.tipo as tipo_unidad,
  i.turno as turno_deteccion,
  date_trunc('month', i.detectada_at) as mes,
  count(*) as cantidad
from incidencia_fallas f
join incidencias i on i.id = f.incidencia_id
join unidades u on u.id = i.unidad_id
join tipos_falla t on t.id = f.tipo_falla_id
left join particularidades p on p.id = f.particularidad_id
group by 1, 2, 3, 4, 5, 6;
